### PR TITLE
prepare for qtconsole-base

### PR DESCRIPTION
**Pull request by jaimergp**
MNT: Re-rendered with conda-build 3.21.4, conda-smithy 3.16.1, and conda-forge-pinning 2021.12.30.03.08.12

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

We are preparing `pyside` variants of napari, but since this is a direct dependency and it depends on `qtconsole` and this depends on `pyqt`, `pyqt` is brought into the environment too. This should depend on `qtconsole-base` (submitted [here](https://github.com/conda-forge/qtconsole-feedstock/pull/46)) instead, so the Python bindings can be chosen freely.

Do not merge until https://github.com/conda-forge/qtconsole-feedstock/pull/46 has been merged too.

### CODE REVIEW

**Comment by jaimergp** [comment]
@sofroniewn, @jni, @tlambert03 - ready for review!

**Review by tlambert03 — APPROVED** [review]
LGTM

**Comment by tlambert03** [comment]
still in draft... do you want a merge on this?

**Comment by jaimergp** [comment]
Oops, sorry about the draft. Yes, it can be merged. It shouldn't change anything for us, other than not having pyqt pulled all the time, even if pyside is requested.

**Pull request merged**
